package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1

import lombok.ToString;

/**
 * Commande generated by hbm2java
 */
@ToString(of = {"contenuAdditionnel", "idFacture", "idTva", "priceHt", "priceTt"})
public class Commande  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private String contenuAdditionnel;
     private int idFacture;
     private int idTva;
     private float priceHt;
     private float priceTt;

    public Commande() {
    }

	
    public Commande(int idFacture, int idTva, float priceHt, float priceTt) {
        this.idFacture = idFacture;
        this.idTva = idTva;
        this.priceHt = priceHt;
        this.priceTt = priceTt;
    }
    public Commande(String contenuAdditionnel, int idFacture, int idTva, float priceHt, float priceTt) {
       this.contenuAdditionnel = contenuAdditionnel;
       this.idFacture = idFacture;
       this.idTva = idTva;
       this.priceHt = priceHt;
       this.priceTt = priceTt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getContenuAdditionnel() {
        return this.contenuAdditionnel;
    }
    
    public void setContenuAdditionnel(String contenuAdditionnel) {
        this.contenuAdditionnel = contenuAdditionnel;
    }
    public int getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(int idFacture) {
        this.idFacture = idFacture;
    }
    public int getIdTva() {
        return this.idTva;
    }
    
    public void setIdTva(int idTva) {
        this.idTva = idTva;
    }
    public float getPriceHt() {
        return this.priceHt;
    }
    
    public void setPriceHt(float priceHt) {
        this.priceHt = priceHt;
    }
    public float getPriceTt() {
        return this.priceTt;
    }
    
    public void setPriceTt(float priceTt) {
        this.priceTt = priceTt;
    }




}


