package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1



/**
 * Comporter generated by hbm2java
 */
public class Comporter  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ComporterId id;

    public Comporter() {
    }

    public Comporter(ComporterId id) {
       this.id = id;
    }
   
    public ComporterId getId() {
        return this.id;
    }
    
    public void setId(ComporterId id) {
        this.id = id;
    }




}


