package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1



/**
 * Composer generated by hbm2java
 */
public class Composer  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ComposerId id;

    public Composer() {
    }

    public Composer(ComposerId id) {
       this.id = id;
    }
   
    public ComposerId getId() {
        return this.id;
    }
    
    public void setId(ComposerId id) {
        this.id = id;
    }




}


