package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1

import lombok.ToString;

/**
 * ComposerId generated by hbm2java
 */
@ToString(of = {"idCommande", "idPaiement"})
public class ComposerId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCommande;
     private int idPaiement;

    public ComposerId() {
    }

    public ComposerId(int idCommande, int idPaiement) {
       this.idCommande = idCommande;
       this.idPaiement = idPaiement;
    }
   
    public int getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(int idCommande) {
        this.idCommande = idCommande;
    }
    public int getIdPaiement() {
        return this.idPaiement;
    }
    
    public void setIdPaiement(int idPaiement) {
        this.idPaiement = idPaiement;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComposerId) ) return false;
		 ComposerId castOther = ( ComposerId ) other; 
         
		 return (this.getIdCommande()==castOther.getIdCommande())
 && (this.getIdPaiement()==castOther.getIdPaiement());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCommande();
         result = 37 * result + this.getIdPaiement();
         return result;
   }   


}


