package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1



/**
 * ComporterId generated by hbm2java
 */
public class ComporterId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCommande;
     private int idProduitService;

    public ComporterId() {
    }

    public ComporterId(int idCommande, int idProduitService) {
       this.idCommande = idCommande;
       this.idProduitService = idProduitService;
    }
   
    public int getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(int idCommande) {
        this.idCommande = idCommande;
    }
    public int getIdProduitService() {
        return this.idProduitService;
    }
    
    public void setIdProduitService(int idProduitService) {
        this.idProduitService = idProduitService;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComporterId) ) return false;
		 ComporterId castOther = ( ComporterId ) other; 
         
		 return (this.getIdCommande()==castOther.getIdCommande())
 && (this.getIdProduitService()==castOther.getIdProduitService());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCommande();
         result = 37 * result + this.getIdProduitService();
         return result;
   }   


}


