package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1

import lombok.ToString;

/**
 * Concerner generated by hbm2java
 */
@ToString(of = {"idFacture", "idVendeur", "idClient"})
public class Concerner  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idFacture;
     private int idVendeur;
     private int idClient;

    public Concerner() {
    }

    public Concerner(int idFacture, int idVendeur, int idClient) {
       this.idFacture = idFacture;
       this.idVendeur = idVendeur;
       this.idClient = idClient;
    }
   
    public int getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(int idFacture) {
        this.idFacture = idFacture;
    }
    public int getIdVendeur() {
        return this.idVendeur;
    }
    
    public void setIdVendeur(int idVendeur) {
        this.idVendeur = idVendeur;
    }
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }




}


