package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1


import java.util.Date;

import lombok.ToString;

/**
 * Facture generated by hbm2java
 */
@ToString(of = {"idLangue", "date", "idCommande"})
public class Facture  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private int idLangue;
     private Date date;
     private int idCommande;

    public Facture() {
    }

    public Facture(int idLangue, Date date) {
       this.idLangue = idLangue;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdLangue() {
        return this.idLangue;
    }
    
    public void setIdLangue(int idLangue) {
        this.idLangue = idLangue;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * @return the idCommande
     */
    public int getIdCommande() {
        return idCommande;
    }

    /**
     * @param idCommande the idCommande to set
     */
    public void setIdCommande(int idCommande) {
        this.idCommande = idCommande;
    }




}


