package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1

import lombok.ToString;

/**
 * Langue generated by hbm2java
 */
@ToString (of = {"nom", "libelle", "idDevise"})
public class Langue  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private String nom;
     private String libelle;
     private int idDevise;

    public Langue() {
    }

    public Langue(String nom, String libelle, int idDevise) {
       this.nom = nom;
       this.libelle = libelle;
       this.idDevise = idDevise;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public int getIdDevise() {
        return this.idDevise;
    }
    
    public void setIdDevise(int idDevise) {
        this.idDevise = idDevise;
    }




}


