package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1

import lombok.ToString;

/**
 * Paiement generated by hbm2java
 */
@ToString(of = {"etat", "reste"})
public class Paiement  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private boolean etat;
     private float reste;

    public Paiement() {
    }

    public Paiement(boolean etat, float reste) {
       this.etat = etat;
       this.reste = reste;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public boolean isEtat() {
        return this.etat;
    }
    
    public void setEtat(boolean etat) {
        this.etat = etat;
    }
    public float getReste() {
        return this.reste;
    }
    
    public void setReste(float reste) {
        this.reste = reste;
    }

    public boolean getEtat() {
    	return this.etat;
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


