package org.easycompta.object;

import lombok.ToString;

// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1



/**
 * Personne generated by hbm2java
 */
@ToString(of = {"numCommercant", "nom", "prenom", "email", "tel", "numRue", "cp", "ville", "type"})
public class Personne  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private String numCommercant;
     private String nom;
     private String prenom;
     private String email;
     private String tel;
     private String numRue;
     private String nomRue;
     private String cp;
     private String ville;
     private int type;

    public Personne() {
    }

    public Personne(String numCommercant, String nom, String prenom, String email, String tel, String numRue, String nomRue, String cp, String ville, int type) {
       this.numCommercant = numCommercant;
       this.nom = nom;
       this.prenom = prenom;
       this.email = email;
       this.tel = tel;
       this.numRue = numRue;
       this.nomRue = nomRue;
       this.cp = cp;
       this.ville = ville;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNumCommercant() {
        return this.numCommercant;
    }
    
    public void setNumCommercant(String numCommercant) {
        this.numCommercant = numCommercant;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getNumRue() {
        return this.numRue;
    }
    
    public void setNumRue(String numRue) {
        this.numRue = numRue;
    }
    public String getNomRue() {
        return this.nomRue;
    }
    
    public void setNomRue(String nomRue) {
        this.nomRue = nomRue;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }




}


