package org.easycompta.object;
// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1

import lombok.ToString;

/**
 * ProduitService generated by hbm2java
 */
//@Entity(name="ProduitService")
//@NamedQuery(
//        name="findAllProduitServicesOrderAsc",
//        query="SELECT ps FROM ProduitService ps ORDER BY ps.nom ASC"
//)
//@NamedQuery(name="getOrdersId", 
//			query="SELECT c.id FROM Comporter c WHERE c.id_produit_service = :idS")
@ToString(of= {"nom", "montantHt", "quantite"})
public class ProduitService  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private String nom;
     private float montantHt;
     private int quantite;

    public ProduitService() {
    }

    public ProduitService(String nom, float montantHt, int quantite) {
       this.nom = nom;
       this.montantHt = montantHt;
       this.quantite = quantite;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public float getMontantHt() {
        return this.montantHt;
    }
    
    public void setMontantHt(float montantHt) {
        this.montantHt = montantHt;
    }
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }




}


