package org.easycompta.object;

import lombok.ToString;

// Generated 18 avr. 2018 22:21:51 by Hibernate Tools 4.3.1



/**
 * Tva generated by hbm2java
 */
@ToString(of= {"pourcentage", "libelle"})
public class Tva  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private float pourcentage;
     private String libelle;

    public Tva() {
    }

    public Tva(float pourcentage, String libelle) {
       this.pourcentage = pourcentage;
       this.libelle = libelle;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public float getPourcentage() {
        return this.pourcentage;
    }
    
    public void setPourcentage(float pourcentage) {
        this.pourcentage = pourcentage;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


